SELECT 
  "nokia_HOPS".name,
  "managedObject_HOPS",
  string_agg(replace("managedObject_distName_parent",'PLMN-PLMN/RNC-',''),'-') AS rnc_list,
  COUNT(name) AS count, 
  "nokia_HOPS"."AdjsHCSpriority", 
  "nokia_HOPS"."AdjsHCSthreshold", 
  "nokia_HOPS"."AdjsPenaltyTime", 
  "nokia_HOPS"."AdjsQoffset1", 
  "nokia_HOPS"."AdjsQoffset2", 
  "nokia_HOPS"."AdjsQqualMin", 
  "nokia_HOPS"."AdjsQrxlevMin", 
  "nokia_HOPS"."AdjsTempOffset1", 
  "nokia_HOPS"."AdjsTempOffset2", 
  "nokia_HOPS"."EcNoAveragingWindow", 
  "nokia_HOPS"."EnableInterRNCsho", 
  "nokia_HOPS"."EnableRRCRelease", 
  "nokia_HOPS"."HHOMarginAverageEcNo", 
  "nokia_HOPS"."HHOMarginPeakEcNo", 
  --"nokia_HOPS"."HOPSChangeOrigin", 
  "nokia_HOPS"."HSDPAAvailabilityIur", 
  "nokia_HOPS"."HSUPAAvailabilityIur", 
  "nokia_HOPS"."ReleaseMarginAverageEcNo", 
  "nokia_HOPS"."ReleaseMarginPeakEcNo"
FROM 
  public."nokia_HOPS"
GROUP BY
  "nokia_HOPS".name,
  "managedObject_HOPS",
  "nokia_HOPS"."AdjsHCSpriority", 
  "nokia_HOPS"."AdjsHCSthreshold", 
  "nokia_HOPS"."AdjsPenaltyTime", 
  "nokia_HOPS"."AdjsQoffset1", 
  "nokia_HOPS"."AdjsQoffset2", 
  "nokia_HOPS"."AdjsQqualMin", 
  "nokia_HOPS"."AdjsQrxlevMin", 
  "nokia_HOPS"."AdjsTempOffset1", 
  "nokia_HOPS"."AdjsTempOffset2", 
  "nokia_HOPS"."EcNoAveragingWindow", 
  "nokia_HOPS"."EnableInterRNCsho", 
  "nokia_HOPS"."EnableRRCRelease", 
  "nokia_HOPS"."HHOMarginAverageEcNo", 
  "nokia_HOPS"."HHOMarginPeakEcNo", 
  --"nokia_HOPS"."HOPSChangeOrigin", 
  "nokia_HOPS"."HSDPAAvailabilityIur", 
  "nokia_HOPS"."HSUPAAvailabilityIur", 
  "nokia_HOPS"."ReleaseMarginAverageEcNo", 
  "nokia_HOPS"."ReleaseMarginPeakEcNo"
ORDER BY 
  "managedObject_HOPS"::int,
  COUNT("nokia_HOPS".name) DESC;