DROP TABLE IF EXISTS t_remotefddcell_generic_create;
CREATE TABLE t_remotefddcell_generic_create AS

SELECT 
  snap3g_remotefddcell.rnc, 
  snap3g_rnc.clusterid, 
  snap3g_rnc.provisionedsystemrelease, 
  tmp_remotefddcell_namenotlikenokia.name AS remotefddcell,
  snap3g_remotefddcell.remotefddcell AS info_old_name,
  snap3g_remotefddcell.alarmprioritytableconfclassid, 
  snap3g_remotefddcell.cacprioritytableconfclassid, 
  snap3g_remotefddcell.cpichecnothresholdinterferencemargincs, 
  snap3g_remotefddcell.cpichecnothresholdinterferencemargincsps, 
  snap3g_remotefddcell.cpichecnothresholdinterferencemarginps, 
  snap3g_remotefddcell.cpichecnothresholdinterferencemarginsmallcellhocs, 
  snap3g_remotefddcell.cpichecnothresholdinterferencemarginsmallcellhocsps, 
  snap3g_remotefddcell.cpichecnothresholdinterferencemarginsmallcellhops, 
  snap3g_remotefddcell.cpichecnothresholdinterferencemarginsmallcellnonhocs, 
  snap3g_remotefddcell.cpichecnothresholdinterferencemarginsmallcellnonhocsps, 
  snap3g_remotefddcell.cpichecnothresholdinterferencemarginsmallcellnonhops, 
  snap3g_remotefddcell.dlfrequencynumber, 
  snap3g_remotefddcell.edchharqcombiningcapability, 
  snap3g_remotefddcell.edchminsfcapability, 
  snap3g_remotefddcell.enhancedpsrabbadradiosmartedchresourceusageactivation, 
  snap3g_remotefddcell.fallbackpolicyuponcacfailureondrnc, 
  snap3g_remotefddcell.hcsprio_connectedmode, 
  snap3g_remotefddcell.hcsprio_idlemode, 
  snap3g_remotefddcell.hoconfclassid, 
  snap3g_remotefddcell.iscacenhancementonpsrabmodificationallowed, 
  snap3g_remotefddcell.iscpcdtxdrxmodeallowed, 
  snap3g_remotefddcell.iscsroperation, 
  snap3g_remotefddcell.iscsspeechoverhspaallowed, 
  snap3g_remotefddcell.isdl64qamallowed, 
  snap3g_remotefddcell.isedchallowed, 
  snap3g_remotefddcell.isedchtti2msallowed, 
  snap3g_remotefddcell.isfastl1synchronizationallowed, 
  snap3g_remotefddcell.ishsdpaallowed, 
  snap3g_remotefddcell.ishsservingcellchangeimprovallowed, 
  snap3g_remotefddcell.isinterferencehofailcalldropallowed, 
  snap3g_remotefddcell.ismacehscapable, 
  snap3g_remotefddcell.ismaciisallowed, 
  snap3g_remotefddcell.isqchatallowed, 
  snap3g_remotefddcell.issmallcell, 
  snap3g_remotefddcell.issrboverhspaenabled, 
  snap3g_remotefddcell.isvoipoverhspaallowed, 
  snap3g_remotefddcell.isvtcallblockatmobilityoncellallowed, 
  snap3g_remotefddcell.isvtcallblockoncellallowed, 
  snap3g_remotefddcell.localcellid, 
  snap3g_remotefddcell.locationareacode, 
  snap3g_remotefddcell.maxallowedultxpower_connectedmode, 
  snap3g_remotefddcell.maxallowedultxpower_idlemode, 
  snap3g_remotefddcell.measurementconfclassid, 
  snap3g_remotefddcell.mobilecountrycode, 
  snap3g_remotefddcell.mobilenetworkcode, 
  snap3g_remotefddcell.multirabbadradiosmartedchresourceusageactivation, 
  snap3g_remotefddcell.multirabsmartedchresourceusageactivation, 
  snap3g_remotefddcell.neighbouringfddcellid, 
  snap3g_remotefddcell.neighbouringrncid, 
  snap3g_remotefddcell.primaryscramblingcode, 
  snap3g_remotefddcell.qhcs_connectedmode, 
  snap3g_remotefddcell.qhcs_idlemode, 
  snap3g_remotefddcell.qqualmin_connectedmode, 
  snap3g_remotefddcell.qqualmin_idlemode, 
  snap3g_remotefddcell.qrxlevmin_connectedmode, 
  snap3g_remotefddcell.qrxlevmin_idlemode, 
  snap3g_remotefddcell.rdnid, 
  snap3g_remotefddcell.reserved0, 
  snap3g_remotefddcell.reserved1, 
  snap3g_remotefddcell.reserved2, 
  snap3g_remotefddcell.reserved3, 
  snap3g_remotefddcell.reserved4, 
  snap3g_remotefddcell.reserved5, 
  snap3g_remotefddcell.reserved6, 
  snap3g_remotefddcell.reserved7, 
  snap3g_remotefddcell.routingareacode, 
  snap3g_remotefddcell.ulfrequencynumber, 
  snap3g_remotefddcell.useoptimizededchharqretransatcelledge, 
  snap3g_remotefddcell.userspecificinfo
FROM 
  public.tmp_remotefddcell_namenotlikenokia, 
  public.snap3g_remotefddcell, 
  public.snap3g_rnc
WHERE 
  tmp_remotefddcell_namenotlikenokia.rnc = snap3g_remotefddcell.rnc AND
  tmp_remotefddcell_namenotlikenokia.remotefddcell = snap3g_remotefddcell.remotefddcell AND
  snap3g_remotefddcell.rnc = snap3g_rnc.rnc
ORDER BY
  snap3g_remotefddcell.rnc,
  tmp_remotefddcell_namenotlikenokia.name;
